### DISCUSSION TITLE
Docker hub Images

### DISCUSSION THREAD

**Discussion by rehanone** [mat-sz/filedrop-web#17] [General]
I was able to build and create these 2 images on docker hub:

- [rehanone/filedrop-ws](https://hub.docker.com/repository/docker/rehanone/filedrop-ws)
- [rehanone/filedrop-web](https://hub.docker.com/repository/docker/rehanone/filedrop-web)

However, I could not get filedrop-web to work there is no way to override the ARG in the Docker compose file when using an image. Here is my `docker-compose.yml`

```yml
---
version: '3.8'

networks:
  fd-net:
    driver: bridge

services:
  ws:
    image: rehanone/filedrop-ws:${SERVER_VERSION}
    container_name: 'filedrop-ws'
    networks:
      - fd-net
    environment:
      WS_HOST: 0.0.0.0
      WS_BEHIND_PROXY: true
      TURN_MODE: hmac
      TURN_SERVER: turn:${HOST}
      TURN_USERNAME: filedrop
      TURN_SECRET: ${TURN_SECRET}
    restart: unless-stopped

  web:
    image: rehanone/filedrop-web:${APP_VERSION}
    container_name: 'filedrop-web'
    networks:
      - fd-net
    environment:
      REACT_APP_TITLE: ${TITLE}
      REACT_APP_SERVER: wss://${HOST}:${PORT}/ws/
      REACT_APP_USE_BROWSER_ROUTER: 1
    restart: unless-stopped

  coturn:
    image: ghcr.io/coturn/coturn:edge-alpine
    container_name: 'filedrop-coturn'
    network_mode: host
    command: '--use-auth-secret --static-auth-secret=${TURN_SECRET} --no-tls --no-dtls'
    restart: unless-stopped

```

I think passing these 3 from ARG to  ENV in the Dockerfile should fix this but I am not sure if they have to be there at build time:
```
      REACT_APP_TITLE: ${TITLE}
      REACT_APP_SERVER: wss://${HOST}:${PORT}/ws/
      REACT_APP_USE_BROWSER_ROUTER: 1
```
